"""Added created_at to Transaction model

Revision ID: 604608665275
Revises: cbb6a31fce88
Create Date: 2025-08-05 22:45:58.373520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604608665275'
down_revision = 'cbb6a31fce88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
